name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build app
        run: mvn clean package

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: "target/hello-0.0.1-SNAPSHOT.jar"
            target: "/home/ec2-user/"
            overwrite: true
      - name: Restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill java || true
            nohup java -jar /home/ec2-user/*.jar > app.log 2>&1 &
