name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build app
        run: mvn clean package

      - name: Verify build output
        run: ls -l target

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/hello-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"
          overwrite: true

      - name: Stop old app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 2m
          script: |
            pkill -f "hello-0.0.1-SNAPSHOT.jar" || true
            rm -f /home/ec2-user/demo-0.0.1-SNAPSHOT.jar || true

      - name: Start new app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 2m
          script: |
            cd /home/ec2-user
            nohup java -jar /home/ec2-user/hello-0.0.1-SNAPSHOT.jar > /home/ec2-user/app.log 2>&1 < /dev/null &
            sleep 5
            tail -n 50 /home/ec2-user/app.log || true
